<!DOCTYPE html>
<html>
    <head>
        <title><?= $this->escape($this->meta_title) ?></title>
        <meta name="keywords" content="<?= $this->escape($this->meta_keywords) ?>"/> 
        <meta name="description" content="<?= $this->escape($this->meta_description) ?>"/> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="shortcut icon" href="/image/favicon.ico"/>
        <link rel="stylesheet" type="text/css" href="/css/index.css"/>
        <link rel="stylesheet" type="text/css" href="/css/supersized.core.css"/>
        <script type="text/javascript" src="/js/jquery.tools.min.js"></script>
        <script type="text/javascript" src="/js/supersized.core.3.2.1.min.js"></script>
        <script type="text/javascript">
            jQuery(function ($) {
                $.supersized({
                    slides: [{
                        image: '/image/bg_splash_1.jpg'
                    }]
                });
            });
        </script>
    </head>
    <body class="index">
        <div id="bg_header">
            <div id="header">
                <div id="logo">
                    <a href="/">
                        <img src="/image/bodysolid_logo.png" alt="Body Solid" border="0" />
                    </a>
                </div>
                <div id="topnav">
<?= $this->menu ?>
                </div>
                <div id="cart">
<?= $this->cart ?>
                </div>
                <div id="search_bar">
<?= $this->search ?>
                </div>
                <div id="mainnav">
<?= $this->catalogue ?>
                </div>
            </div>
        </div>
        <div id="content">
            <div id="main_feat">
                <div id="slidecaption">
                    <div id="splash_box_1"><a href="/product/free_weights" class="free"></a><a href="/product/stack_loaded" class="stack"></a></div>
                </div>
            </div>
            <div id="feat_products">
<?= $this->content ?>
            </div>
        </div>
        <div id="bg_footer">
            <div id="footer">
<?= $this->line ?>
            </div>
        </div>
    </body>
</html>
