<?= Adminko\View::block('module/product/subnav', $this) ?>

<div id="feature_cms">
    <script src="/js/fancybox/jquery.fancybox-1.3.4.js"></script>
    <link rel="stylesheet" type="text/css" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <script>
        $(document).ready(function() {
            $(".fancybox-thumb").fancybox({
                prevEffect	: 'none',
                nextEffect	: 'none',
                helpers	: {
                    title	: {
                        type: 'outside'
                    },
                    overlay	: {
                        opacity : 0.8,
                        css : {
                            'background-color' : '#000'
                        }
                    },
                    thumbs	: {
                        width	: 50,
                        height	: 50
                    }
                }
            });
        });
    </script>

    <h2>Упражнения</h2>
<?php foreach ($this->getExercisesList() as $exercise) { ?>
    <div id="item_options">
        <div id="item_options_img">
            <a href="<?= $exercise->getExerciseImage() ?>" title="<?= $exercise->getExerciseTitle() ?>"><img src="<?= $exercise->getExerciseImage() . '/r/80/80' ?>" alt="<?= $exercise->getExerciseTitle() ?>"></a>
        </div>
        <div id="item_options_spec">
            <p style="color: white"><?= $exercise->getExerciseTitle() ?></p>
            <?= $exercise->getExerciseDescription() ?> 
        </div>
    </div>
<?php } ?>
</div>
<div class="clear"></div>