<?= Adminko\View::block('module/product/subnav', $this) ?>

<div id="feature_cms">
    <h2>Характеристики</h2>
    <ul>
<?php   foreach ($this->getPropertyList() as $property) { ?>
<?php       if (!is_empty($property->getPropertyValue())) { ?>
        <li>
            <?= $property->getPropertyTitle() ?>: <?= $property->getPropertyValue() ?> <?= $property->getPropertyUnit() ?>
        </li>
<?php       } ?>
<?php   } ?>
    </ul>
</div>
<div class="clear"></div>