Вас приветствует интернет-магазин Bodysolid!<br/><br/>
Благодарим за Ваш заказ. Мы получили следующую информацию:<br/><br/>
<?php $item_index = 1; ?>
<?php foreach ($this->cart->get() as $item) { ?>
<?php 		$product_item = Adminko\Model\Model::factory('product')->get($item->id); ?>
<?= $item_index ?>. <?= $product_item->getProductTitle() ?> - <?= $item->quantity ?> x <?= $item->price ?> (<?= $item->price ?> р.)<br/>
<?php 		$item_index++; ?>
<?php } ?>
<br/>
Общая стоимость заказа: <?= $this->cart->getSum() ?> р.<br/><br/>

ФИО: <?= $this->fromRequest('name') ?><br/>
Телефон: <?= $this->fromRequest('phone') ?><br/>
Email: <?= $this->fromRequest('email') ?><br/>
Адрес: <?= $this->fromRequest('address') ?><br/>
Комментарий: <?= $this->fromRequest('comment') ?><br/>
<br/>
В ближайшее время с Вами свяжется менеджер нашего магазина, чтобы уточнить время доставки и сборки товара.<br/><br/>

С уважением,<br/>
Интернет-магазин Bodysolid
